# File: docker-compose.yml

networks:
  internal:
    name: internal
    #driver: bridge
    external: true

services:
  rdtclient:
    container_name: rdtclient # Real-Debrid Torrent Client
    image: rogerfar/rdtclient
    networks:
      - internal
    profiles:
      - all
      - install
    volumes:
      - ./shared-media-downloads:/data/downloads
      - ./services/rdt-client/db:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
    #ports:
    #  - '6500:6500' # REMOVE IN PRODUCTION

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    profiles:
      - all
      - install
    networks:
      - internal
    #ports:
    #  - "8096:8096" #REMOVE IN PRODUCTION
    volumes:
      -  ./shared-media-downloads:/downloads
      -  ./services/jellyfin/config:/config
      -  ./services/jellyfin/cache:/cache
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    profiles:
      - all
      - install
    networks:
      - internal
    ports:
      - "8082:8080" # REMOVE IN PRODUCTION GET TROUGH NGINX
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      -  ./shared-media-downloads:/downloads
      -  ./services/qbittorrent/config/qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    profiles:
      - all
      - install
    networks:
      - internal
    #ports: # REMOVE IN PRODUCTION
    #  - "7878:7878"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/radarr/config/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    profiles:
      - install
      - all
    networks:
      - internal
   #ports:  # REMOVE IN PRODUCTION
    #  - "8989:8989"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/sonarr/config/sonarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    profiles:
      - install
      - all
    networks:
      - internal
    #ports: # REMOVE IN PRODUCTION
    #  - "6767:6767"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/bazarr/config/bazarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    profiles:
      - install
      - all
    networks:
      - internal
    #ports: # REMOVE IN PRODUCTION
    #  - "9117:9117"
    volumes:
      - ./services/jackett/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
