# File: docker-compose.yml

networks:
  internal:
    name: internal
    #driver: bridge
    external: true

services:
  rdtclient:
    container_name: rdtclient # Real-Debrid Torrent Client
    image: rogerfar/rdtclient
    networks:
      - internal
    profiles:
      - all
      - install
    volumes:
      - ./media-services/shared-media-downloads:/data/downloads
      - ./media-services/services/rdt-client/db:/data/db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
    #ports:
    #  - '6500:6500'

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    profiles:
      - all
      - install
    networks:
      - internal
    #ports:
    #  - "8096:8096" # Remove when running through nginx
    volumes:
      -  ./media-services/shared-media-downloads:/downloads
      -  ./media-services/services/jellyfin/config:/config
      -  ./media-services/services/jellyfin/cache:/cache
    restart: unless-stopped


  stremio-web:
    container_name: stremio-web
    image: stremio-web:latest
    profiles:
      - all
      - streaming
    environment:
      - NODE_ENV=production
    #ports:
    #  - "8081:8080"  # Remove when running trough nginx
    build:
      context:  ./media-services/services/stremio-web/stremio-web
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - /usr/bin/vlc:/usr/bin/vlc
    restart: unless-stopped

  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    profiles:
      - all
      - streaming
    networks:
      - internal
    ports:
      - "11470:11470"
    volumes:
      - ./media-services/services/stremio-server/server-storage:/root/.stremio-server
      - /usr/bin/vlc:/usr/bin/vlc
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    profiles:
      - all
      - install
    networks:
      - internal
    ports:
      - "8082:8080" # Remove when running through nginx
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      -  ./media-services/shared-media-downloads:/downloads
      -  ./media-services/services/qbittorrent/config/qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    profiles:
      - all
      - install
    networks:
      - internal
    ports:
      - "7878:7878"
    volumes:
      - ./media-services/shared-media-downloads:/downloads
      - ./media-services/services/radarr/config/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "8989:8989"
    volumes:
      - ./media-services/shared-media-downloads:/downloads
      - ./media-services/services/sonarr/config/sonarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "6767:6767"
    volumes:
      - ./media-services/shared-media-downloads:/downloads
      - ./media-services/services/bazarr/config/bazarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "9117:9117"
    volumes:
      - ./media-services/services/jackett/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
