# File: toplevel-ui/docker-compose.yml

version: '3.8'

networks:
  internal:
    external: true

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    volumes:
      - ./auth-service:/app
    environment:
      - NODE_ENV=production
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
