# File: docker-compose.yml

networks:
  internal:
    name: internal
    driver: bridge


services:
  #wireguard:
  #  image: linuxserver/wireguard
  #  container_name: wireguard
  #  cap_add:
  #    - NET_ADMIN
  #    - SYS_MODULE
  #  volumes:
  #    - ./wireguard/config:/config
  #    - /lib/modules:/lib/modules
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/London
  #    - SERVERURL=your_vpn_server.com # Change to your VPN server address
  #    - SERVERPORT=51820
  #    - PEERS=1 # Number of peers, adjust as necessary
  #    - PEERDNS=auto
  #    - INTERNAL_SUBNET=10.13.13.0
  #  sysctls:
  #    - net.ipv4.conf.all.src_valid_mark=1
  #  restart: unless-stopped
  #  networks:
  #    - internal

  # jackett addon for stremio
  #stremio-jackett:
  #  image: belmeg/stremio-addon-jackett
  #  container_name: stremio-jackett
  #  networks:
  #    - internal
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Etc/UTC
  #    - ADDON_NAME=stremio_jacket
  #  depends_on:
  #    - jackett
  #  ports:
  #    - "3000:3000" # Remove when running trough nginx
  #  restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    restart: unless-stopped
 
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - internal
    ports:
      - "8096:8096" # Remove when running through nginx
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/cache:/cache
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - internal
    ports:
      - "8191:8191"  # Remove when running trough nginx
    restart: unless-stopped

  stremio-web:
    container_name: stremio-web
    image: stremio-web:latest
    build:
      context: .
      dockerfile: services/stremio-web/Dockerfile
      cache_from:
        - stremio-web:latest
    networks:
      - internal
    ports:
      - "8081:8080"  # Remove when running trough nginx
    restart: unless-stopped
  
  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    ports:
      - "11470:11470"
    volumes:
      - ./services/stremio-server/server-storage:/root/.stremio-server
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      - internal
    ports:
      - "8080:8080" # Remove when running through nginx
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/qbittorrent/config/qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - internal
    ports:
      - "7878:7878"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/radarr/config/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - internal
    ports:
      - "8989:8989"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/sonarr/config/sonarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    networks:
      - internal
    ports:
      - "6767:6767"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/bazarr/config/bazarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
      - internal
    ports:
      - "9117:9117"
    volumes:
      - ./services/jackett/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    network_mode: host
    volumes:
      - ./services/fail2ban/logs/nginx:/var/log/nginx
      - ./services/fail2ban/logs/qbittorrent:/var/log/qbittorrent
      - ./services/fail2ban/logs/radarr:/var/log/radarr
      - ./services/fail2ban/logs/sonarr:/var/log/sonarr
      - ./services/fail2ban/logs/bazarr:/var/log/bazarr
      - ./services/fail2ban/logs/jackett:/var/log/jackett
      - ./services/fail2ban/logs/stremio-web:/var/log/stremio-web
      - ./services/fail2ban/logs/stremio-server:/var/log/stremio-server
      - ./services/fail2ban:/config/fail2ban
      - ./services/fail2ban/jail.local:/config/fail2ban/jail.local
      - ./services/fail2ban/filter.d:/config/fail2ban/filter.d
    environment:
      - F2B_LOG_LEVEL=INFO
      - F2B_JAIL_LOCAL=/config/fail2ban/jail.local
    restart: unless-stopped

  