
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/cache:/cache
      - ./services/jellyfin/media:/media
      - ./services/jellyfin/downloads:/downloads
    restart: unless-stopped

  stremio-jackett:
    image: belmeg/stremio-addon-jackett
    container_name: stremio-jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ADDON_NAME=stremio_jacket
    depends_on:
      - jackett
    ports:
      - "3000:3000"
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "8191:8191"
    restart: unless-stopped

  stremio-web:
    container_name: stremio-web
    image: stremio-web:latest
    build:
      context: .
      dockerfile: Dockerfile.stremio-web
      cache_from:
        - stremio-web:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
  
  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    ports:
      - "11470:11470"
    volumes:
      - ./services/stremio-server/server-storage:/root/.stremio-server
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
    depends_on:
      - jellyfin
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - "8080:8080" # 8080 host, 8080 container
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./services/qbittorrent/downloads:/downloads
      - ./services/qbittorrent/config/qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - ./services/radarr/downloads:/downloads
      - ./services/radarr/media:/media
      - ./services/radarr/config/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ./services/sonarr/downloads:/downloads
      - ./services/sonarr/media:/media
      - ./services/sonarr/config/sonarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    volumes:
      - ./services/bazarr/downloads:/downloads
      - ./services/bazarr/media:/media
      - ./services/bazarr/config/bazarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - ./services/jackett/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    network_mode: host
    volumes:
      - ./services/fail2ban/logs/nginx:/var/log/nginx
      - ./services/fail2ban/logs/qbittorrent:/var/log/qbittorrent
      - ./services/fail2ban/logs/radarr:/var/log/radarr
      - ./services/fail2ban/logs/sonarr:/var/log/sonarr
      - ./services/fail2ban/logs/bazarr:/var/log/bazarr
      - ./services/fail2ban/logs/jackett:/var/log/jackett
      - ./services/fail2ban/logs/stremio-web:/var/log/stremio-web
      - ./services/fail2ban/logs/stremio-server:/var/log/stremio-server
      - ./services/fail2ban:/config/fail2ban
      - ./services/fail2ban/jail.local:/config/fail2ban/jail.local
      - ./services/fail2ban/filter.d:/config/fail2ban/filter.d
    environment:
      - F2B_LOG_LEVEL=INFO
      - F2B_JAIL_LOCAL=/config/fail2ban/jail.local
    restart: unless-stopped

  