# File: docker-compose.yml

networks:
  internal:
    name: internal
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    profiles:
      - all
      - streaming
      - install
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./nginx/certs/server.crt:/etc/nginx/
      - ./nginx/certs/server.key:/etc/nginx/
      #- ./nginx/certs:/etc/nginx
    restart: unless-stopped

  rdtclient:
    container_name: rdtclient # Real-Debrid Torrent Client
    image: rogerfar/rdtclient
    networks:
      - internal
    profiles:
      - all
      - install
    volumes:
      - ./shared-media-downloads:/data/downloads
      - ./services/rdt-client/db:/data/db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - '6500:6500'

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    profiles:
      - all
      - install
    networks:
      - internal
    #ports:
    #  - "8096:8096" # Remove when running through nginx
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/jellyfin/config:/config
      - ./services/jellyfin/cache:/cache
    restart: unless-stopped


  stremio-web:
    container_name: stremio-web
    image: stremio-web:latest
    profiles:
      - all
      - streaming
    environment:
      - NODE_ENV=production
    #ports:
    #  - "8081:8080"  # Remove when running trough nginx
    build:
      context: ./services/stremio-web/stremio-web
      dockerfile: Dockerfile
    networks:
      - internal
    restart: unless-stopped

  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    profiles:
      - all
      - streaming
    networks:
      - internal
    ports:
      - "11470:11470"
    volumes:
      - ./services/stremio-server/server-storage:/root/.stremio-server
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    profiles:
      - all
      - install
    networks:
      - internal
    ports:
      - "8080:8080" # Remove when running through nginx
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/qbittorrent/config/qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    profiles:
      - all
      - install
    networks:
      - internal
    ports:
      - "7878:7878"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/radarr/config/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "8989:8989"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/sonarr/config/sonarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "6767:6767"
    volumes:
      - ./shared-media-downloads:/downloads
      - ./services/bazarr/config/bazarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    profiles:
      - install
      - all
    networks:
      - internal
    ports:
      - "9117:9117"
    volumes:
      - ./services/jackett/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    profiles:
      - all
      - install
      - streaming
    network_mode: host
    volumes:
      - ./services/fail2ban/logs/nginx:/var/log/nginx
      - ./services/fail2ban/logs/qbittorrent:/var/log/qbittorrent
      - ./services/fail2ban/logs/radarr:/var/log/radarr
      - ./services/fail2ban/logs/sonarr:/var/log/sonarr
      - ./services/fail2ban/logs/bazarr:/var/log/bazarr
      - ./services/fail2ban/logs/jackett:/var/log/jackett
      - ./services/fail2ban/logs/stremio-web:/var/log/stremio-web
      - ./services/fail2ban/logs/stremio-server:/var/log/stremio-server
      - ./services/fail2ban:/config/fail2ban
      - ./services/fail2ban/jail.local:/config/fail2ban/jail.local
      - ./services/fail2ban/filter.d:/config/fail2ban/filter.d
    environment:
      - F2B_LOG_LEVEL=INFO
      - F2B_JAIL_LOCAL=/config/fail2ban/jail.local
    restart: unless-stopped

  