services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=your_vpn_server.com # Change to your VPN server address
      - SERVERPORT=51820
      - PEERS=1 # Number of peers, adjust as necessary
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - interna
  jackett addon for stremio
  stremio-jackett:
    image: belmeg/stremio-addon-jackett
    container_name: stremio-jackett
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ADDON_NAME=stremio_jacket
    depends_on:
      - jackett
    ports:
      - "3000:3000" # Remove when running trough nginx
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - internal
    ports:
      - "8191:8191"  # Remove when running trough nginx
    restart: unless-stopped