
networks:
  stremio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  stremio:
    container_name: stremio
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      IPADDRESS: 192.168.1.2
      DISABLE_HW_ACCEL: 1
    ports:
      - "8081:8080"
      - "11470:11470" # Just one of the two should be enough
      - "12470:12470"
    networks:
      stremio-network:
        ipv4_address: 192.168.1.2
    volumes:
      - "./stremio-server-storage:/root/.stremio-server"

    
