# File: server-services/docker-compose.yml

networks:
  internal:
    name: internal
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    profiles:
      - all
      - streaming
      - install
      - webserver_debug
      - striimu
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./nginx/certs/server.crt:/etc/nginx/certs/server.crt
      - ./nginx/certs/server.key:/etc/nginx/certs/server.key
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    profiles:
      - all
      - install
      - streaming
      - server
      - striimu
    network_mode: host
    volumes:
      - ./fail2ban/logs/nginx:/var/log/nginx
      - ./fail2ban/logs/qbittorrent:/var/log/qbittorrent
      - ./fail2ban/logs/radarr:/var/log/radarr
      - ./fail2ban/logs/sonarr:/var/log/sonarr
      - ./fail2ban/logs/bazarr:/var/log/bazarr
      - ./fail2ban/logs/jackett:/var/log/jackett
      - ./fail2ban/logs/stremio-web:/var/log/stremio-web
      - ./fail2ban/logs/stremio-server:/var/log/stremio-server
      - ./fail2ban:/config/fail2ban
      - ./fail2ban/jail.local:/config/fail2ban/jail.local
      - ./fail2ban/filter.d:/config/fail2ban/filter.d
    environment:
      - F2B_LOG_LEVEL=INFO
      - F2B_JAIL_LOCAL=/config/fail2ban/jail.local
    restart: unless-stopped

  #mailserver:
  #  image: ghcr.io/docker-mailserver/docker-mailserver:latest
  #  container_name: mailserver
  #  hostname: mail.striimu.com
  #  domainname: striimu.com
  #  profiles:
  #    - all
  #    - striimu
  #    #- streaming
  #    - install
  #    - server
  #  env_file: ./server-services/docker-mailserver/mailserver.env
  #  ports:
  #    - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
  #    - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
  #    - "465:465"  # ESMTP (implicit TLS)
  #    - "587:587"  # ESMTP (explicit TLS => STARTTLS)
  #    - "993:993"  # IMAP4 (implicit TLS)
  #  volumes:
  #    - ./server-services/docker-mailserver/mail-data/:/var/mail/
  #    - ./server-services/docker-mailserver/mail-state/:/var/mail-state/
  #    - ./server-services/docker-mailserver/mail-logs/:/var/log/mail/
  #    - ./server-services/docker-mailserver/config/:/tmp/docker-mailserver/
  #    - ./server-services/docker-mailserver/ssl:/tmp/docker-mailserver/ssl:ro
  #    - /etc/localtime:/etc/localtime:ro
  #  stop_grace_period: 1m
  #  cap_add:
  #    - NET_ADMIN
  #  networks:
  #    - internal
  #  healthcheck:
  #    test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
  #    timeout: 3s
  #    retries: 0
