# File: server-services/docker-compose.yml

networks:
  internal:
    name: internal
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    profiles:
      - all
      - streaming
      - install
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/mime.types:/etc/nginx/mime.types
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/proxy_params.conf:/etc/nginx/proxy_params.conf
      - ${PWD}/nginx/certs/server.crt:/etc/nginx/server.crt
      - ${PWD}/nginx/certs/server.key:/etc/nginx/server.key
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    profiles:
      - all
      - install
      - streaming
    network_mode: host
    volumes:
      - ${PWD}/fail2ban/logs/nginx:/var/log/nginx
      - ${PWD}/fail2ban/logs/qbittorrent:/var/log/qbittorrent
      - ${PWD}/fail2ban/logs/radarr:/var/log/radarr
      - ${PWD}/fail2ban/logs/sonarr:/var/log/sonarr
      - ${PWD}/fail2ban/logs/bazarr:/var/log/bazarr
      - ${PWD}/fail2ban/logs/jackett:/var/log/jackett
      - ${PWD}/fail2ban/logs/stremio-web:/var/log/stremio-web
      - ${PWD}/fail2ban/logs/stremio-server:/var/log/stremio-server
      - ${PWD}/fail2ban:/config/fail2ban
      - ${PWD}/fail2ban/jail.local:/config/fail2ban/jail.local
      - ${PWD}/fail2ban/filter.d:/config/fail2ban/filter.d
    environment:
      - F2B_LOG_LEVEL=INFO
      - F2B_JAIL_LOCAL=/config/fail2ban/jail.local
    restart: unless-stopped
