# File: striimu-services/docker-compose.yml

networks:
  internal:
    name: internal
    external: true

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/certs:/certs
      - /app/__pycache__  # Optional: to avoid caching issues
    #env_file:
    #  - ./backend/.env
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    ports:  # FOR DEBUG REMOVE IN PRODUCTION
      - "3000:3000"
    #expose:
    #  - 3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid node_modules override
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    ports:      # FOR DEBUG REMOVE IN PRODUCTION
      - "8080:8080"
    #expose:
    #  - 8080
