# File: striimu-services/docker-compose.yml

networks:
  internal:
    name: internal
    external: true

services:
  backend:
    container_name: backend
    build:
      context: ./striimu-services/backend
      dockerfile: Dockerfile
    volumes:
      - ./striimu-services/backend:/app
      - ./striimu-services/backend/certs:/certs
      - /app/__pycache__  # Optional: to avoid caching issues
    env_file:
      - ./striimu-services/backend/.env
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    ports:  # FOR DEBUG REMOVE IN PRODUCTION
      - "3000:3000"
    expose:
      - "3000"

  frontend:
    container_name: frontend
    build:
      context: ./striimu-services/frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VUE_APP_BACKEND_URL=http://backend:3000
    volumes:
      - ./striimu-services/frontend:/app
      - /app/node_modules  # Avoid node_modules override
      - /app/dist
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    #ports:      # FOR DEBUG REMOVE IN PRODUCTION
    #  - "8080:8080"
    expose:
      - "8080"
