# File: striimu-services/docker-compose.yml

networks:
  internal:
    name: internal
    #driver: bridge
    external: true

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/backend:/app
    env_file:
      - ${PWD}/backend/.env
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    #ports:
    #  - "6500:80"
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    expose:
      - 8080
