# File: striimu-services/docker-compose.yml

networks:
  internal:
    name: internal
    external: true

services:
  backend:
    build:
      context: ./striimu-services/backend
      dockerfile: Dockerfile
    volumes:
      - ./striimu-services/backend:/app
      - ./striimu-services/backend/certs:/certs
    env_file:
      - ./striimu-services/backend/.env
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    expose:
      - 3000

  frontend:
    build:
      context: ./striimu-services/frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - internal
    restart: unless-stopped
    profiles:
      - all
      - streaming
      - install
      - striimu
    expose:
      - 8080
